version: '3'
services: 
  jenkins:
    container_name: jenkins
    build: 
      context: .
    ports: 
      - "8080:8080"
    volumes: 
      - ./docker/jenkins/:/var/jenkins_home
      - ./docker/etc/apt/:/docker/etc/apt/CHROME_VERSION